version: '3'
services:
  db:
    image: postgres:15
    container_name: db-test
    env_file: .env.test
    environment:
      - POSTGRES_DB=test_programs
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./test_db/pgdata:/var/lib/postgresql/data
      - ./api/migrations/2023-07-04-082332_init/up.sql:/docker-entrypoint-initdb.d/initdb1.sql
  redis:
    image: redis
    container_name: redis-test
    env_file: .env.test
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "./test_db/redisdata:/data"
      - "./redis.conf:/conf/redis.conf"
    command: sh -c 'redis-server /conf/redis.conf --requirepass "$${TEST_REDIS_PASSWORD}"'
